#!/bin/bash
# chkconfig: 0356 27 62
# description: Script is used to manage kafka server

# Source function library.
. /etc/init.d/functions

PIDS=$(ps ax | grep -i 'kafka\.Kafka' | grep java | grep -v grep | awk '{print $1}')

start() {
    NEXT_WAIT_TIME=0
    until [ ! -z "$(netstat -tuplen | grep 9092)" ] || [ $NEXT_WAIT_TIME -eq 10 ]; do
       sleep $(( NEXT_WAIT_TIME++ ))
       nohup /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/server.properties > /opt/kafka/logs/kafka-server.log 2>&1 &
    done
    touch /var/lock/subsys/kafka
}

stop() {
    /opt/kafka/bin/kafka-server-stop.sh
    rm -f /var/lock/subsys/kafka
}

case "$1" in
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)
       if [ -z "$PIDS" ]; then
           echo "No kafka server is running"
           exit 1
       else
           echo "Kafka is running. Pid is $PIDS"
           exit 0
       fi
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0	