#!/bin/bash
# chkconfig: 2345 23 80
# description: Script is used to manage spark cluster servers

# Source function library.
. /etc/init.d/functions

PIDS=$(ps ax | grep -i 'spark' | grep java | grep -v grep | awk '{print $1}')

start() {
    /opt/spark/sbin/./start-all.sh
}

stop() {
    /opt/spark/sbin/./stop-all.sh
}

case "$1" in
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)
       if [ -z "$PIDS" ]; then
           echo "No spark clusters are running"
           exit 1
       else
           echo 'Master pid:' $(ps ax | grep -i 'spark\.deploy\.master\.Master' | grep java | grep -v grep | awk '{print $1}')
           echo 'Worker pids:' $(ps ax | grep -i 'spark\.deploy\.worker\.Worker' | grep java | grep -v grep | awk '{print $1}')

           exit 0
       fi
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0